### ISSUE TITLE
二进制编码顺序可能影响卦象判定

### ISSUE THREAD

**Issue by lazyracket** [freizl/yijing#14]
在实际起卦过程中，我们是从下往上确定卦象的六爻。比如，起卦(x) 分别得到：

> 初爻 阴，0
> 二爻 阳，1
> 三爻 阴，0
> 四爻 阳，1
> 五爻 阳，1
> 上爻 阳，1

一般会将上述记录为"010111"，查询 `64gua.js`，将得到`需 ䷄`。

但按照传统，起卦(x) 对应的应该是`讼 ䷅`。

建议：考虑切换到传统的从下到上编码（需卦或更新为 "111010"），这将有助于防止混淆并确保在算卦实现中正确识别卦象。

**Comment by freizl** [comment]
我记得按照传统记法，应该是这样的

```
上爻 阳，1
五爻 阳，1
四爻 阳，1
三爻 阴，0
二爻 阳，1
初爻 阴，0
```

初爻在最下
然后至于怎么表示二进制，我确实也是纠结过。我的想法是初爻在“低”的位置，所以上述的卦会是 `111010`

**Comment by freizl** [comment]
> 嗯，如果卦的二级制处理方式保持不变的话，爻辞的呈现顺序是否需要调整呢？现在爻辞是先写的初爻。
> 如果要对应，考虑到爻辞的数量，以及存在乾卦用九和坤卦用六，好像调整卦的二进制更简便一些。

Good point!
这需要一致！ 我找机会修改一下

**Comment by freizl** [comment]
Fixed in 
bf5d0db8cfbd382d219b62275ef6e36c3f97e237
fff17510e05c4a54d7b2d0b44a5f3a876b903e97

and released `@freizl/yijing-2.0.0`.

Let me know any issues.
